# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /usr/src/app

# install app dependencies
COPY package.json /usr/src/app

RUN npm install --silent

# add app
COPY . /usr/src/app
RUN npm run build


EXPOSE 5000

# start app
CMD ["node", "server.js"]