# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /usr/src/app

# install app dependencies
COPY package.json .

RUN npm install --silent

RUN npm run build
# add app
COPY . ./


EXPOSE 5000

# start app
CMD ["node", "server.js"]