# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /react-starter/react-starter

# add `/app/node_modules/.bin` to $PATH
ENV PATH /react-starter/react-starter/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --ignore-engines
RUN yarn global add react-scripts@1.1.0
# add app
COPY . .

EXPOSE 8080
# start app
CMD ["yarn", "start"]
